### ISSUE TITLE
Chromedriver Download after Chrome 115

### ISSUE THREAD

**Issue by tobka777** [Andrej1b/zedd2#105]
Download des Chromedriver funktioniert nicht.

Nach Chrome 115 haben sich die Downloadlinks geändert:
"If you are using Chrome version 115 or newer, please consult[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading." https://chromedriver.chromium.org/downloads

Resources:
- https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
- https://googlechromelabs.github.io/chrome-for-testing/#stable

**Comment by CapChristianK** [comment]
@tobka777 Weißt Du zufällig wer das bis wann beheben könnte?

**Comment by CapChristianK** [comment]
Umgehungslösung: _Man muss sich aktuell manuell den Chrome Treiber herunterladen und den aktuell genutzten unter C:\Users\<USERNAME>\AppData\Roaming\chromedriver durch den richtigen ersetzen.

Entsprechende Treiber findet man unter https://googlechromelabs.github.io/chrome-for-testing/#stable_

**Comment by tobka777** [comment]
Ich habe den Bug im Release v2.12.1 gefixt!
https://github.com/tobka777/zedd2/releases/tag/v2.12.1
