### ISSUE TITLE
Fehlermeldungen besser anzeigen

### ISSUE THREAD

**Issue by OliverNeff** [Andrej1b/zedd2#115]
**Ist:** 
Fehlermeldungen werden nur kurz über eine Leiste am unteren Rand angezeigt. Bei uns im Team ist es derzeit so, dass Tickets nach Ende des Sprints relativ schnell geschlossen werden und ZEDD daher nicht mehr auf dieses Ticket buchen kann.
Als Fehlermeldung wird kurz in rot angezeigt, dass er ein bestimmtes Label nicht finden konnte. Das Browserfenster wird dabei ziemlich schnell beendet.

**Soll:**
Es soll ein Overlay angezeigt mit den betroffenen Tickets (Fehlern). Das Overlay soll so lange bestehen bis man es bestätigt.

**Comment by tobka777** [comment]
Gut wäre, wenn die Fehlermeldungen länger stehen bleiben und sie man mit einem X schließen muss.
